version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dnd_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dnduser
      POSTGRES_PASSWORD: dndpass
      POSTGRES_DB: dnddb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
